export const onlinePlayersReportDataMock = [
  {
    name: "Leanne Graham",
    customerId: 1,
    email: "Sincere@april.biz",
    currency: 'EUR - Euro',
    realBalance: 650,
    bonusBalance: 120,
    country: 'United Kingdom',
    lifetimeDeposits: 12000,
    lifetimeWithdrawals: 14500,
    openBets: 300,
    Ngr: 180,
    loggedInFor: '00:06:15'
  },
  {
    name: "Ervin Howell",
    customerId: 2,
    email: "Shanna@melissa.tv",
    currency: 'EUR - Euro',
    realBalance: 590,
    bonusBalance: 550,
    country: 'Italy',
    lifetimeDeposits: 25000,
    lifetimeWithdrawals: 17800,
    openBets: 150,
    Ngr: 250,
    loggedInFor: '00:45:36'
  },
  {
    name: "Clementine Bauch",
    customerId: 3,
    email: "Nathan@yesenia.net",
    currency: 'EUR - Euro',
    realBalance: 465,
    bonusBalance: 300,
    country: 'United Kingdom',
    lifetimeDeposits: 53000,
    lifetimeWithdrawals: 47000,
    openBets: 600,
    Ngr: 1200,
    loggedInFor: '00:17:45'
  },
  {
    name: "Patricia Lebsack",
    customerId: 4,
    email: "Julianne.OConner@kory.org",
    currency: 'EUR - Euro',
    realBalance: 670,
    bonusBalance: 1200,
    country: 'United Kingdom',
    lifetimeDeposits: 26450,
    lifetimeWithdrawals: 33630,
    openBets: 2000,
    Ngr: 1800,
    loggedInFor: '00:06:04'
  },
  {
    name: "Chelsey Dietrich",
    customerId: 5,
    email: "Lucio_Hettinger@annie.ca",
    currency: 'EUR - Euro',
    realBalance: 620,
    bonusBalance: 950,
    country: 'Italy',
    lifetimeDeposits: 14360,
    lifetimeWithdrawals: 8765,
    openBets: 2200,
    Ngr: 1600,
    loggedInFor: '00:37:37'
  },
  {
    name: "Mrs. Dennis Schulist",
    customerId: 6,
    email: "Karley_Dach@jasper.info",
    currency: 'EUR - Euro',
    realBalance: 690,
    bonusBalance: 600,
    country: 'Sweden',
    lifetimeDeposits: 6900,
    lifetimeWithdrawals: 3400,
    openBets: 1000,
    Ngr: 1900,
    loggedInFor: '00:48:59'
  },
  {
    name: "Kurtis Weissnat",
    customerId: 7,
    email: "Telly.Hoeger@billy.biz",
    currency: 'EUR - Euro',
    realBalance: 360,
    bonusBalance: 340,
    country: 'United Kingdom',
    lifetimeDeposits: 15640,
    lifetimeWithdrawals: 12580,
    openBets: 500,
    Ngr: 650,
    loggedInFor: '00:27:33'
  },
  {
    name: "Nicholas Runolfsdottir V",
    customerId: 8,
    email: "Sherwood@rosamond.me",
    currency: 'EUR - Euro',
    realBalance: 840,
    bonusBalance: 670,
    country: 'United Kingdom',
    lifetimeDeposits: 36900,
    lifetimeWithdrawals: 33200,
    openBets: 550,
    Ngr: 500,
    loggedInFor: '00:55:19'
  },
  {
    name: "Glenna Reichert",
    customerId: 9,
    email: "Chaim_McDermott@dana.io",
    currency: 'EUR - Euro',
    realBalance: 380,
    bonusBalance: 800,
    country: 'Sweden',
    lifetimeDeposits: 12790,
    lifetimeWithdrawals: 14500,
    openBets: 1400,
    Ngr: 1200,
    loggedInFor: '00:12:03'
  },
  {
    name: "Clementina DuBuque",
    customerId: 10,
    email: "Rey.Padberg@karina.biz",
    currency: 'EUR - Euro',
    realBalance: 620,
    bonusBalance: 1800,
    country: 'Italy',
    lifetimeDeposits: 18900,
    lifetimeWithdrawals: 16540,
    openBets: 1500,
    Ngr: 1800,
    loggedInFor: '00:17:'
  }
];
