export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED'

export const REQUEST_UPDATE_USER_PENDING = 'REQUEST_USER_PENDING'
export const REQUEST_UPDATE_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_UPDATE_USER_FAILED = 'REQUEST_USER_FAILED'

export const REQUEST_CURREENT_USER_PENDING = 'REQUEST_CURREENT_USER_PENDING'
export const REQUEST_CURREENT_USER_SUCCESS = 'REQUEST_CURREENT_USER_SUCCESS'
export const REQUEST_CURREENT_USER_FAILED = 'REQUEST_CURREENT_USER_FAILED'