export const form_data = {
  email: "",
  firstName: "",
  lastName: "",
  status: "",
  affiliateId: "",
  country: "",
  createdAt: "",
  loginStatus: "",
  lastBetTime: "",
  balance: "",
  promo_balance: "",
  kycStatus: "",
  siteID: "",
};

export const errors = {
  email: false,
  firstName: false,
  lastName: false,
  status: false,
  affiliateId: false,
  country: false,
  createdAt: false,
  loginStatus: false,
  lastBetTime: false,
  balance: false,
  promo_balance: false,
  kycStatus: false,
  siteID: false,
};
export const errorMessages = {
  email: "",
  firstName: "",
  lastName: "",
  status: "",
  affiliateId: "",
  country: "",
  createdAt: "",
  loginStatus: "",
  lastBetTime: "",
  balance: "",
  promo_balance: "",
  kycStatus: "",
  siteID: "",
};
