export const CHANHGE_LOGIN_FORM = "CHANHGE_LOGIN_FORM";
export const CHANGE_PASSWORD_VISIBILITY = "CHANGE_PASSWORD_VISIBILITY";
export const CLEAR_LOGIN_FORM = "CLEAR_LOGIN_FORM";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_LOGGED_IN = "UPDATE_LOGGED_IN";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO ";
