export const REQUEST_PLAYERS_PENDING = 'REQUEST_PLAYERS_PENDING'
export const REQUEST_PLAYERS_SUCCESS = 'REQUEST_PLAYERS_SUCCESS'
export const REQUEST_PLAYERS_FAILED = 'REQUEST_PLAYERS_FAILED'

export const REQUEST_PLAYERS_UPDATE_PENDING = 'REQUEST_PLAYERS_UPDATE_PENDING'
export const REQUEST_PLAYERS_UPDATE_SUCCESS = 'REQUEST_PLAYERS_UPDATE_SUCCESS'
export const REQUEST_PLAYERS_UPDATE_FAILED = 'REQUEST_PLAYERS_UPDATE_FAILED'