export const REQUEST_PLAYER_PENDING = 'REQUEST_PLAYER_PENDING'
export const REQUEST_PLAYER_SUCCESS = 'REQUEST_PLAYER_SUCCESS'
export const REQUEST_PLAYER_FAILED = 'REQUEST_PLAYER_FAILED'

export const REQUEST_UPDATE_PLAYER_PENDING = 'REQUEST_PLAYER_PENDING'
export const REQUEST_UPDATE_PLAYER_SUCCESS = 'REQUEST_PLAYER_SUCCESS'
export const REQUEST_UPDATE_PLAYER_FAILED = 'REQUEST_PLAYER_FAILED'

